### ISSUE TITLE
ungültige LernSax-E-Mail-Adresse

### ISSUE THREAD

**Issue by lukitheflusspferd** [AntonioAlbt/kepler_app#1]
Eine Zahl im Benutzernamen lässt die E-Mail-Adresse ungültig werden.
Bsp.: maxm@jkgc.lernsax.de ist gültig, maxm2@jkgc.lernsax.de jedoch nicht.

**Comment by Gamer153** [comment]
Danke für den Hinweis, ich fixe das gleich.
Darf ich noch fragen, wie du dieses Repo hier gefunden hast? Ich wusste nicht, dass die App schon Nutzer hat, und es würde mich interessieren, woher du davon weißt :)

**Comment by lukitheflusspferd** [comment]
Ich bin der, der einfach Mal im Info-Unterricht war und Probleme mit der PaintBox hatte. Deinen Benutzernamen habe ich von der Schulball-Webseite.
Du machst das toll!
