### ISSUE TITLE
Unvollständiger Vertretungsplan 

### ISSUE THREAD

**Issue by lukitheflusspferd** [AntonioAlbt/kepler_app#10]
Eine Vertretung, welche auf dem Bildschirm in der Eingangshalle angezeigt wird, taucht in der App nicht auf.

![20240513_102102~2.jpg](https://github.com/AntonioAlbt/kepler_app/assets/142101905/e59ba5d3-4443-4f9d-9908-08bc9c2181e4)

![Screenshot_20240513_102323.jpg](https://github.com/AntonioAlbt/kepler_app/assets/142101905/330fbf84-e70a-4ce8-a9f8-5c127d52ebdb)

![Screenshot_20240513_102339.jpg](https://github.com/AntonioAlbt/kepler_app/assets/142101905/564a5646-b1be-4492-b3a1-b96f31823c8e)

Das könnte evtl. daran liegen, dass die Vertretung nichts ändert.
Ist das so gewollt dass solche Vertretungen nicht angezeigt werden?

MfG

**Comment by AntonioAlbt** [comment]
Da die "Alle Vertretungen"-Seite nicht tatsächlich die Datenquelle für alle Vertretungen (die gleiche wie der Bildschirm) verwendet, sondern nur Vertretungen anzeigt, die als geändert markiert sind, wird eine solche Vertretung nicht dort angezeigt.
Und im Stundenplan selbst wird die bestimmt angezeigt, aber da nichts geändert ist, siehst du ja keinen Unterschied egal ob jetzt diese "Vertretung" verwendet wird oder nicht (und es ist ja auch egal).

**Comment by lukitheflusspferd** [comment]
Danke für die schnelle Antwort
