### ISSUE TITLE
Ungültige LernSax-E-Mail-Adresse ("Zweitadresse" von Andre-Gym)

### ISSUE THREAD

**Issue by grericht** [AntonioAlbt/kepler_app#11]
**Fehlerbeschreibung**
Ich kann mich leider nicht anmelden. Da der Älteste Sohn auf dem André Gym ist, habe ich für einen gemeinsamen Zugriff auf beide Kinder eine xyz.xyz.e2@andregymnasium.lernsax.de Adresse. Mit den ZUgangsdaten erhalte ich die Fehlermeldung: "Ungültige LernSax-E-Mail-Adresse"

**Schritte zum Reproduzieren**
kann ich nachliefern wenn Bedarf

**Screenshots**
kann ich bei Bedarf noch nachreichen

**Dein Gerät (bitte ausfüllen)**
 - Gerät: Redmi Note 12
 - Betriebssystem mit Version: Android 14
 - App-Version (siehe "Über diese App"): 2.1.3
 - App-Ursprung: PlaStore

**Log-Ausschnitt**
nicht möglich

**Comment by AntonioAlbt** [comment]
Die App überprüft standardmäßig die Zugehörigkeit zum Kepler-Gym. mithilfe der Zugehörigkeit zur Institution - hast du bei Lernsax im Internet die Möglichkeit, auf die Institutionsseite des JKGs zuzugreifen? Die sollte mit in der Klassenauswahl erscheinen.

**Comment by grericht** [comment]
Ich kann bei Schule neben dem André das JKG auswählen. Die Zugehörigkeit sollte also stimmen. Trotzdem kann ich mich nicht anmelden.

**Comment by AntonioAlbt** [comment]
Das ist jetzt angepasst, sollte innerhalb des nächsten Tags im Play Store veröffentlicht werden.

**Comment by grericht** [comment]
abgewiesener Login in der Kepler App
![01](https://github.com/AntonioAlbt/kepler_app/assets/128326089/5626596e-b209-47cb-b9f1-792b836936f4)
Zugang im Browser mit den gleichen Zugangsdaten - Start im André
![03](https://github.com/AntonioAlbt/kepler_app/assets/128326089/9ca3a725-6c53-409c-a845-17b10efc365d)
Klink auf Raum wechseln.
![02](https://github.com/AntonioAlbt/kepler_app/assets/128326089/c6c1890c-5869-48b9-925f-38c4f6259ef1)

Danke für das Update. Hab es gerade installiert aber komme immer noch nicht in die App. Grundlegend ist sie doch auch für Eltern gedacht? oder nur für die Schüler:innen selber?

**Comment by AntonioAlbt** [comment]
Ja, die App ist auch für Eltern gedacht - mit JKG-LernSax-Mails geht das auch einfach, aber wenn du mit deinem Login trotzdem Mitglied im JKG bist müsste die App das eigentlich erkennen.

Mir ist jetzt aber grad beim durchlesen aufgefallen, warum deine Mail noch als ungültig zählt: wenn sie vom Schema abc.xyz.e2@andregymnasium.lernsax.de ist, wird sie von der App abgelehnt, weil diese aktuell nur Emails auf die Endung ".eltern" oder ähnliche mit "." zulässt.

Da werde ich in den nächsten Tagen nochmal ein Update machen.

**Comment by grericht** [comment]
Hab noch 3 screenshots angefügt.
Im browser komme ich immer erst im André raus und muss den raum wechseln zum Kepler. Hoffe dies stört die Kepler App nicht?
Danke dir auf jeden Fall für den super support! Ist wirklich ein großartiges Projekt an dem ich gerne partizipieren mag wenn ich endlich Zugang habe ;)

**Comment by AntonioAlbt** [comment]
Ich habe nochmal ein Update für die App veröffentlicht (wird in den nächsten Stunden im Play Store veröffentlicht), damit sollte das Problem gelöst sein. Falls nicht, bitte nochmal schreiben.

**Comment by grericht** [comment]
Hab das neueste Update installiert und getestet. Leider funktioniert es immer noch nicht aber mit anderer Meldung. Nun scheint er sich wenigstens zu versuchen sich anzumelden. Leider erkennt er nicht, das ich im JKG bin.
![Screenshot_2024-05-21-21-50-24-978_de keplerchemnitz kepler_app](https://github.com/AntonioAlbt/kepler_app/assets/128326089/bcbcd747-f30f-49a5-87d2-664b7e28df54)

**Comment by AntonioAlbt** [comment]
Hm, das habe ich nicht berücksichtigt - tut mir leid, dass sich das noch weiter verzögert, aber da muss ich nochmal ein Update machen.

**Comment by grericht** [comment]
Jetzt funktioniert es. Vielen Dank!
