### ISSUE TITLE
Debugaufzeichnungen können in iOS nicht geteilt werden

### ISSUE THREAD

**Issue by lukitheflusspferd** [AntonioAlbt/kepler_app#13]
**Fehlerbeschreibung**
Beim Betätigen des Buttons "Datei teilen" passiert nichts.

**Schritte zum Reproduzieren**
1. Auf einem iOS-Gerät eine beliebige Debugaufzeichnung öffnen
2. Den Button "Datei teilen" betätigen.
3. Den Dialog bestätigen.
4. Fehler: Nichts passiert

**Screenshots**
https://github.com/AntonioAlbt/kepler_app/assets/142101905/08a75a89-bd5f-4fa4-8d02-ed90ef675f71

**Mein Gerät**
 - Gerät: iPad Air 5. Generation 
 - Betriebssystem mit Version: iOS 17.4.1
 - App-Version 2.2.1 (56)
 - App-Ursprung: App Store

**Log-Ausschnitt**
[26.05.2024 10:07] [E] (platform-dispatcher-error) PlatformException(error, sharePositionOrigin: argument must be set, {{0, 0}, {0, 0}} must be non-zero and within coordinate space of source view: {{0, 0}, {820, 1180}}, null, null):
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
<asynchronous suspension>
#2      MethodChannelShare.shareXFiles (package:share_plus_platform_interface/method_channel/method_channel_share.dart:108)
<asynchronous suspension>
#3      _LogViewPageState.build.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:kepler_app/libs/logging.dart:365)
<asynchronous suspension>
#4      _LogViewPageState.build.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:kepler_app/libs/logging.dart:367)
<asynchronous suspension>

**Vermutliche Ursache**
Die Funktion `Share.shareXFiles` in [logging.dart, Zeile 365](https://github.com/AntonioAlbt/kepler_app/blob/705f22329780a0c13d23fbe85fd32008e267f520/lib/libs/logging.dart#L365) hat das Argument `sharePositionOrigin`, welches aber nicht verwendet wird:
![image](https://github.com/AntonioAlbt/kepler_app/assets/142101905/516e42d7-44df-4fef-bc73-c0c119e7a484)

Dieses Argument hat aber keine Standardbelegung, womit dieses Argument mit `null` belegt bleibt:
![image](https://github.com/AntonioAlbt/kepler_app/assets/142101905/fca81f13-60b8-4484-809b-4501ec5bdeab)

Damit hat iOS vermutlich ein Problem.

**Comment by lukitheflusspferd** [comment]
Ich würde ja versuchen, das zu beheben, weiß aber nicht, wie ich iOS-Apps testen kann.

**Comment by AntonioAlbt** [comment]
Ich kann das leider auf meinem Test-iPhone auf der aktuellen App Store-Version nicht reproduzieren. Der Fehler scheint dann außerdem bei `share_plus_platform_interface` (bzw. `share_plus`) zu liegen, und ich habe nicht genug Ahnung von iOS-Entwicklung um zu wissen, ob es vielleicht einen Unterschied zwischen iPhone und iPad in der Hinsicht gibt.

Video vom Test-iPhone:
<video src="https://github.com/AntonioAlbt/kepler_app/assets/148400502/90058891-f847-471a-aec3-e23eaaf540ef">

**Comment by lukitheflusspferd** [comment]
Die Screenshots stammen aus dem Code von share_plus. Hab leider abgesehen davon keine Ahnung, woran es dann liegen könnte. 
Hab es noch auf einem iPad 9. Generation versucht, auch hier kein Erfolg.

**Comment by lukitheflusspferd** [comment]
Nach [diesem Fehler](https://github.com/fluttercommunity/plus_plugins/issues/1640) sollte das das Problem beheben.

**Comment by AntonioAlbt** [comment]
Ich veröffentliche die nächsten Tage das Update im App Store.

**Comment by AntonioAlbt** [comment]
Das Update ist jetzt live, kannst du ausprobieren ob es jetzt geht?

**Comment by lukitheflusspferd** [comment]
Funktioniert jetzt, danke.
