### ISSUE TITLE
Neue Lernsax-Adressen der neuen 5. Klassen ungültig 

### ISSUE THREAD

**Issue by lukitheflusspferd** [AntonioAlbt/kepler_app#2]
In einem Elternbrief einer neuen 5. Klasse gab es in der Verteilerliste fast nur Adressen wie "maxm5-4.eltern@jkgc.lernsax.de".
Scheinbar wird Namen, die es schon gibt, nun keine Zahl, sondern die Klassennummer angehängt.
Sollte das so bleiben (davon gehe ich aus), wäre der Bindestrich bei der In-App Anmeldung ungültig.
Ich werde mich morgen bei Herrn S. darüber informieren.

**Comment by Gamer153** [comment]
Das wäre ja ein ziemlich seltsames Namensschema, dann müssten sich die Mails ja jedes Jahr ändern... aber vielen Dank, wenn du Herr Seifert fragst.

**Comment by lukitheflusspferd** [comment]
Das sind wohl doch nur temporäre Adressen, weil zum Zeitpunkt der Erstellung noch irgendwelche Schülerdaten fehlten. Die werden noch durch normale ersetzt.
