### ISSUE TITLE
Stundenplan wird nicht korrekt eingeloggt

### ISSUE THREAD

**Issue by lukitheflusspferd** [AntonioAlbt/kepler_app#21]
**Fehlerbeschreibung**
In Anschluss an #20 funktionierte zwar die Anmeldung mit Lernsax, der Stundenplan konnte aber nicht automatisch angemeldet werden. Nach erfolgreicher Eingabe der Anmeldedaten öffnete sich die Startseite; im Widget "Heutige Vertretungen" stand die Fehlermeldung, ich sei nicht angemeldet, obwohl ich das wenige Sekunden zuvor getan hatte. Auch der Lernsaxbereich war gesperrt. Das Drücken auf "jetzt anmelden" im Widget führte zu #20. Ein Neustart an dieser Stelle beseitigte den Fehler. Ein anderes Mal führte ein Neustart zur letzten Seite im Anmeldedialog(wird eingeloggt...), was dann zu "Unbekannte Seite" führte --> unvorhersehbares Verhalten der App
--> Schlussfolgerung: #20 führte nicht zu einer erfolgreichen Anmeldung
Ein erneutes Zurücksetzen der App über die Einstellungen war hier jedoch erfolgreich. (Bei späteren Reproduktionsversuchen aber auch wieder nicht)

**Schritte zum Reproduzieren**
Eine funktionierende App zurücksetzen, führt über #20  zu diesem Fehler.

**Screenshots**
![Datei1](https://github.com/user-attachments/assets/b3915fd0-e906-4ae8-bc54-51b2d61d654a)
![Datei2](https://github.com/user-attachments/assets/1c06ba2c-67ce-44c0-904a-a23d6451a6fb)

**Dein Gerät:**
siehe #20 

**Log-Ausschnitt**
Neue Log-Einträge seit #20:

[02.10.2024 11:27] [D] (ls-api-call) called set_session, set_focus, get_messages
[02.10.2024 11:27] [D] (pendel) fetched pendel data from https://pendel.vlant.de/logging
[02.10.2024 11:27] [E] (lernsax) type 'Null' is not a subtype of type 'List<dynamic>' in type cast:
#0      getTasks (package:kepler_app/libs/lernsax.dart:390)
<asynchronous suspension>
#1      _HomeLSTasksWidgetState.loadData (package:kepler_app/tabs/home/widgets/ls_tasks_home.dart:145)
<asynchronous suspension>

[02.10.2024 11:27] [E] (lernsax) type 'Null' is not a subtype of type 'List<dynamic>' in type cast:
#0      getNotifications (package:kepler_app/libs/lernsax.dart:350)
<asynchronous suspension>
#1      _HomeLSNotifsWidgetState.loadData (package:kepler_app/tabs/home/widgets/ls_notifs_home.dart:144)
<asynchronous suspension>

[02.10.2024 11:35] [E] (news-data) HandshakeException: Connection terminated during handshake:

[02.10.2024 11:35] [D] (pendel) fetched pendel data from https://pendel.vlant.de/logging
[02.10.2024 11:35] [D] (pendel) fetched pendel data from https://pendel.vlant.de/logging
[02.10.2024 11:35] [D] (cal-data) loaded 1 events from https://www.kepler-chemnitz.de/wp-json/tribe/events/v1/events?start_date=2024-10-01&end_date=2024-10-31

**Comment by lukitheflusspferd** [comment]
Ich habe eine Bildschirmaufnahme, die will GitHub aber gerade nicht annehmen.

**Comment by AntonioAlbt** [comment]
Das hängt bestimmt auch mit den nur teilweise gelöschten Daten zusammen. Vielleicht bleibt irgendwas von der LernSax-Anmeldung übrig und sorgt dann für Fehler.

**Comment by AntonioAlbt** [comment]
Das wird mit dem Problem aus #20 zusammenhängen, ich markiere das auch erstmal als gefixed.

**Comment by lukitheflusspferd** [comment]
Ich warte auf die nächste Version im App-Store und schaue dann mal, ob dann alles funktioniert.
