### ISSUE TITLE
Klausurplan Anzeige lässt sich nicht scrollen

### ISSUE THREAD

**Issue by Moertenlol** [AntonioAlbt/kepler_app#23]
Die Anzeige im Klausuren-Plan dehnt sich wie als wäre das schon am unteren Ende aber lässt sich nicht bis zum Ende scrollen

https://github.com/user-attachments/assets/bc5b523f-ca56-440f-b4bb-5b52b581ca3a

**Comment by AntonioAlbt** [comment]
Der Fix ist im Update 2.8.0, sollte in ein paar Tagen auf allen Plattformen veröffentlicht sein.
