### ISSUE TITLE
Falsche Schattierung im Menü

### ISSUE THREAD

**Issue by lukitheflusspferd** [AntonioAlbt/kepler_app#3]
Die Schattierung des aktuell ausgewählten Untermenüs wird nicht korrekt verschoben.
Das passiert, wenn ein Bereich ausgeklappt wird und ein darunter liegendes Menü ausgewählt ist.

https://github.com/Gamer153/kepler_app/assets/142101905/8661473f-62f7-45c2-8711-a5886905e981

**Comment by Gamer153** [comment]
Ich hab keine komplett gute Lösung gefunden, also springt jetzt der Drawer jetzt einfach ein ganz kleines bisschen runter, wenn man das ausklappt, weil dann scheint das ordentlich dargestellt zu werden. Es fällt zwar während der Ausklapp-Animation noch auf, aber ich denk mal, dass die meisten sowieso den Eintrag selbst zum Ausklappen antippen werden, also hoffe ich einfach mal, das fällt nicht so auf.
