### ISSUE TITLE
Sentry funktioniert nicht 

### ISSUE THREAD

**Issue by lukitheflusspferd** [AntonioAlbt/kepler_app#4]
Beim Versuch, Sentry zu aktivieren, schließt sich die App, Sentry ist beim Neustart aber trotzdem nicht aktiviert.

**Comment by AntonioAlbt** [comment]
Gut, dass sich das gelöst hat, aber eigentlich ist Sentry jetzt entweder in Beta-Builds zwingend aktiviert oder in normalen Builds nicht mehr verfügbar, weil das datenschutzrechtlich nicht so toll wäre.
