### ISSUE TITLE
Falscher StuPlan

### ISSUE THREAD

**Issue by lukitheflusspferd** [AntonioAlbt/kepler_app#5]
Der Stundenplan auf der Seite "Dein Stundenplan" stimmt nicht mit dem Klassenplan und dem Online-Stundenplan überein.![Screenshot_20231203_205349_Chrome.jpg](https://github.com/AntonioAlbt/kepler_app/assets/142101905/9f08a41d-51e0-4c20-9297-6a0512929486)

https://github.com/AntonioAlbt/kepler_app/assets/142101905/147a0291-f80e-4574-93a6-8a410dcdf082

**Comment by lukitheflusspferd** [comment]
@AntonioAlbt

**Comment by AntonioAlbt** [comment]
Hast du alle Kurse angewählt? Kannst du mir mal einen Screenshot von der Kursauswahl schicken?

**Comment by AntonioAlbt** [comment]
@lukitheflusspferd

**Comment by lukitheflusspferd** [comment]
Du hast Recht, im Rahmen des StuPlanwechsels vor einigen Wochen wurden anscheinend einige Kurse zurückgesetzt. Seltsamerweise war ein Kurs dabei, bei dem sich nichts geändert hatte.
Ich schlage eine Benachrichtigung vor, die vor automatisch geänderten Kursen warnt.
Danke für deine Zeit.
