### ISSUE TITLE
BUG: White Screen Bug Reihenfolge

### ISSUE THREAD

**Issue by crispy-caesus** [AntonioAlbt/kepler_app#6]
# Expected Behaviour
Items im Reihenfolge Screen können alle problemlos sicht- und unsichtbar gemacht werden

# Current Behaviour
Kepler-News unsichtbar und sichtbar zu machen erzeugt leicht transparenten White-Screen

# Steps to Reproduce
1. Reihenfolge Button auf "Aktuelle News" drücken
2. Auf "Kepler-News" Verstecken-Knopf drücken
3. Auf "Kepler-News" Wieder-Anzeigen-Knopf drücken
4. Whitescreen

![WhiteScreen](https://github.com/AntonioAlbt/kepler_app/assets/114518720/3f1fce3a-9d81-4386-8609-11b65ca48f64)

Andere Items waren auch betroffen, ich konnte das Muster jedoch nicht erkennen

# Context (Environment)
## AppVersion
1.8.1
## Log
[Kepler-App-Log-21_02_2024.txt](https://github.com/AntonioAlbt/kepler_app/files/14356859/Kepler-App-Log-21_02_2024.txt)
## Weitere Umgebung
**Betriebsystem:**
- HyperOS (1.0.2.0.UMGEUXM)
- Android 14 UKQ1.230917.001

**Handymodell:**
- Xiaomi Redmi Note 12 (23021RAA2Y)

**Comment by crispy-caesus** [comment]
Es kommt auch bei Verschiebungen der Reihenfolge teilweise vor, wobei ich aber wieder nicht das Muster erkennen kann

**Comment by AntonioAlbt** [comment]
Hi, danke für den detaillierten Bug-Report, der ist wirklich hilfreich. Ich habe ein ähnliches Problem zwar schon selbst gehabt, war aber immer nur irgend ein Fehler beim Rendering in Flutter (was bei solchen Fehlern dann das betreffende Objekt durch ein grauen Screen ersetzt). Allerdings dachte ich nicht, dass man den wirklich erreichen kann, und die Flutter-Exceptions landen leider noch nicht im Log.
Ich versuche dann in den nächsten Tagen mal, den zu reproduzieren und noch zu fixen.

Darf ich noch fragen, woher du von meiner App erfahren hast? Die ist ja noch gar nicht wirklich veröffentlicht :)

**Comment by crispy-caesus** [comment]
ah, gut zu wissen, 

> Darf ich noch fragen, woher du von meiner App erfahren hast? Die ist ja noch gar nicht wirklich veröffentlicht :)

Ich habe schon öfters bei z. B. dem Foucaultschen Pendel VLANT Studios gesehen, also hab ich nachdem ich dieses wieder auf dem Schulballposter gesehen hab, mir mal die Website aus langer Weile angeguckt, und bin auf dieses Repo gestoßen.
