### ISSUE TITLE
Klassenleiterstunden werden nicht angezeigt 

### ISSUE THREAD

**Issue by lukitheflusspferd** [AntonioAlbt/kepler_app#7]
![Screenshot_20240209_121839.jpg](https://github.com/AntonioAlbt/kepler_app/assets/142101905/81bd8543-3e0d-4da7-974b-3663dbd12d9f)

![Screenshot_20240209_121124.jpg](https://github.com/AntonioAlbt/kepler_app/assets/142101905/ee45048f-4533-469b-947b-bb81d8be9da5)

Im persönlichen Stundenplan werden Klassenleiterstunden nicht angezeigt, im Klassenplan jedoch schon.
Im Stundenauswahlmenü des persönlichen Plans gab es keine Auswahloption für KL-Stunden.

**Comment by AntonioAlbt** [comment]
Danke für den Bugreport - alle Kurse ohne spezielle IDs (wie Klassenleiterstunden) werden jetzt angezeigt, egal was man in der Auswahl gewählt hat.
