### ISSUE TITLE
Pendelwidget Anzeigefehler

### ISSUE THREAD

**Issue by lukitheflusspferd** [AntonioAlbt/kepler_app#8]
Bei der Darstellung des Pendelwidgets kommt es zu einem Pixeloverflow.
![Screenshot_20240320_192113](https://github.com/AntonioAlbt/kepler_app/assets/142101905/da05f16f-e0c5-4561-b8d7-f0b3fe45f4f3)

Im Logfile findet sich dazu folgendes:
"[E] (flutter-error) A RenderFlex overflowed by 2.0 pixels on the bottom.:"
[Kepler-App-Log-20_03_2024.txt](https://github.com/AntonioAlbt/kepler_app/files/14671097/Kepler-App-Log-20_03_2024.txt)

Auf meinem Handy (Samsung Galaxy A53 5G) tritt dieser Fehler immer auf.

Versuche, den Fehler in einer VM mit gleichen Eigenschaften, gleichen Widgeteinstellungen und gleichem Code zu reproduzieren, scheiterten.

Android-Version: One UI 6.0, Android 14
App-Version: 2.0.2

Anmerkung: im Log tritt auch noch ein anderer Fehler zusammenhängend mit dem Kalenderwidget auf, welchen ich aber nicht zuordnen kann
Der Unterschied zwischen VM und echtem Gerät liegt in der Samsung spezifischen One UI

Frau S. hat uns leider genau im vierten Vortragsblock den Fototermin reingedrückt, weswegen ich leider nicht zuschauen kann. Ich wünsche Dir trotzdem viel Erfolg.

**Comment by AntonioAlbt** [comment]
Danke für den Bugreport, und schade das du nicht zu meinem Vortrag kommen kannst :(

Ich habe zwar auch ein One-UI-Gerät (S20 FE 5G), aber bei mir tritt der Fehler nicht auf - ich hab absolut keine Ahnung, warum das bei deinem so ist, und ich hatte zwar erst auf Bildschirmgröße getippt, aber dein Bildschirm sieht ja groß genug aus.
Aber ich hab eine Lösungsidee: ich hab zum Testen in `foucault_home.dart` Z. 64/65 und 186/187 für die Columns `mainAxisSize: MainAxisSize.max,` bisher nur lokal hinzugefügt, vielleicht hilft das.
Du kannst das ja entweder selber machen und builden, oder du nimmst die Debug-APK: [Google Drive](https://drive.google.com/file/d/19hWJZhbdQEf3QA3nki7V-BDf3i6ULn_j/view), da ist das schon so. Probier' das mal aus, wenn's geht kann ich das committen.

**Comment by lukitheflusspferd** [comment]
Ich habe deinen Vorschlag ausprobiert (hoffentlich richtig), er hat aber leider zu keinem Ergebnis geführt.


Über den Flutter Inspector habe ich noch ein bisschen rumprobiert (siehe Videos).
Dabei konnte ich das Problem lösen, weiß aber nicht, wie man das im Code umsetzen müsste.

Die Videos starten ungefähr gleichzeitig.
Nach Neustart der App wird der Fehler im Flutter Inspector angezeigt.
Im Bereich Padding kann der Fehler mit "flex: 1" behoben werden.
Für Zahlen >=1 ändert sich nichts.
Im Bereich Stack steht dann aber immer noch "height is unconstrained". 
Das lässt sich mit "flex: 1" bis "flex: 5" beheben.
Dabei verzerrt sich aber die Pendelanzeige.
Dafür erscheint "flex: 4" am besten.

Viele Grüße

https://github.com/AntonioAlbt/kepler_app/assets/142101905/edb330a8-85bc-48ab-a93c-8f0adfd98d8d

https://github.com/AntonioAlbt/kepler_app/assets/142101905/e4af530a-ffa5-4214-bae2-11d2d6b89705

**Comment by lukitheflusspferd** [comment]
Hab jetzt deine APK getestet, hat aber auch nicht funktioniert.
Daraus war aber ersichtlich, dass das auch mit den Standardeinstellungen der App passiert.

**Comment by lukitheflusspferd** [comment]
Der Fehler taucht jetzt nicht mehr auf.
