### ISSUE TITLE
BUG: Ladefehler Stundenplan

### ISSUE THREAD

**Issue by crispy-caesus** [AntonioAlbt/kepler_app#9]
# Current Behavior
- Der Morgige Tag lädt nicht
- Gestern hat der heutige Tag auch nicht geladen
- Heute werden Änderungen (Wie die Musik Klausur heute) nicht angezeigt -> wohl nur Standartdaten generiert

# Expected Behaviour
- Der Stundenplan kann die nächsten Tage Problemlos laden

# Log
[Kepler-App-Log-11_04_2024.txt](https://github.com/AntonioAlbt/kepler_app/files/14940976/Kepler-App-Log-11_04_2024.txt)

**Comment by crispy-caesus** [comment]
Hier noch Screenshots dazu, die ich leider mit der Mobile Github App nicht in den Issue gekriegt habe 

![Screenshot_2024-04-11-05-51-46-871_de.keplerchemnitz.kepler_app.jpg](https://github.com/AntonioAlbt/kepler_app/assets/114518720/654d1cb1-dc13-412e-8c56-7474b52a74b5)

![Screenshot_2024-04-11-05-51-50-693_de.keplerchemnitz.kepler_app.jpg](https://github.com/AntonioAlbt/kepler_app/assets/114518720/9882804c-0994-4829-8769-de307ad02b08)

**Comment by AntonioAlbt** [comment]
Das sollte gefixed sein, wenn du oben rechts auf das "Aktualisieren"-Icon tippst (oder 1 Tag wartest), weil du irgendwie kaputte Daten im Cache hast.

**Comment by crispy-caesus** [comment]
ah, ja danke, es hat sich wohl nicht automatisch geupdated
